/**
 * Chat Entity Interface
 *
 * Represents a conversation thread in iNoU.
 * - Stored in local SQLite (.inuo.db) by default
 * - Syncable via Colmena like any other entity
 * - CRUD through `semanticDispatcher` + `shell.ts`
 * - Only ONE chat is active at a time
 * - Each chat maintains independent LLM context window
 *
 * Formula: CHAT = {id, title, status, messages[], LLM_context}
 */
export interface Chat {
  /** Unique identifier for the Chat */
  id: string;

  /** Human-friendly title (auto-generated by LLM if not provided) */
  title: string;

  /** Current state of the chat */
  status: "Active" | "Archived" | "Deleted";

  /** Array of message IDs in this chat (reference to chat_messages table) */
  messageIds: string[];

  /** LLM model configuration used for this chat */
  modelType?: string;

  /** User or project ID that owns this chat */
  ownerId?: string;

  /** Chat creation timestamp */
  createdAt: string;

  /** Last modification timestamp */
  updatedAt: string;

  /** Colmena sync metadata */
  cloudSyncId?: string;
  syncVersion?: number;
  syncStatus?: "LOCAL_ONLY" | "SYNCED" | "MODIFIED" | "CONFLICT";
}

/**
 * Chat Message Entity Interface
 *
 * Represents a single message within a chat conversation.
 */
export interface ChatMessage {
  /** Unique identifier for the message */
  id: string;

  /** Reference to the parent Chat ID */
  chatId: string;

  /** Message role: 'user', 'assistant', 'system' */
  role: "user" | "assistant" | "system";

  /** Message content */
  content: string;

  /** Optional message metadata (attachments, formatting, etc.) */
  metadata?: Record<string, any>;

  /** Message creation timestamp */
  createdAt: string;

  /** Colmena sync metadata */
  cloudSyncId?: string;
  syncStatus?: "LOCAL_ONLY" | "SYNCED" | "MODIFIED";
}
